name: 'QUIC Interop Runner Action'
description: ''
author: 'mxinden'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  image-name:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: 'echo "Image name: ${{ inputs.image-name }}"'
      shell: bash
