name: 'QUIC Interop Runner Action'
description: ''
author: 'mxinden'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  image-name:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout quic-interop/quic-interop-runner repository
      uses: actions/checkout@v2
      with:
        repository: 'quic-interop/quic-interop-runner'
        path: 'quic-interop-runner'
    - name: Install dependencies
      run: pip3 install -r quic-interop-runner/requirements.txt
      shell: bash
    - name: Run the interop runner
      run: |
        cd quic-interop-runner
        python3 run.py
      shell: bash
