name: 'QUIC Interop Runner Action'
description: ''
author: 'mxinden'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  image-name:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: sudo apt-get install -y wireshark
      shell: bash
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Enable IPv6 support
      run: sudo modprobe ip6table_filter
      shell: bash
    - run: docker image ls
      shell: bash
    - name: Checkout quic-interop/quic-interop-runner repository
      uses: actions/checkout@v2
      with:
        repository: 'quic-interop/quic-interop-runner'
        path: 'quic-interop-runner'
    - name: Install Python packages
      run: |
        pwd
        ls -la
        cd quic-interop-runner
        pip install -U pip
        pip install -r requirements.txt
      shell: bash
    - name: Run tests
      env:
        CRON: "true"
      run: |
        cd quic-interop-runner
        echo '{"neqo": {"image": "${{ inputs.image-name }}", "url": "https://github.com/mozilla/neqo", "role": "both"}}' > implementations.json
        cat implementations.json
        python run.py -t onlyTests -d
      shell: bash
