on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./
        with:
          image-name: 'ghcr.io/mozilla/neqo-qns:latest'
