on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: mxinden/quic-interop-runner-action@main
        with:
          image-name: 'ghcr.io/mozilla/neqo-qns:latest'
